// <auto-generated />
namespace AvaliadorGastronomico.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModeloInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModeloInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201702241451100_ModeloInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
